load("//toolchains/java:def.bzl", "jar_library")

package(default_visibility = ["//visibility:public"])

jar_library(
    name = "ev3classes",
    jar = "ev3classes.jar",
)

jar_library(
    name = "websocket",
    jar = "Java-WebSocket-1.5.3.jar",
)

jar_library(
    name = "slf4j-api",
    jar = "slf4j-api-1.7.25.jar",
)

jar_library(
    name = "slf4j-simple",
    jar = "slf4j-simple-1.7.25.jar",
)