load("@rules_java//java:defs.bzl", "java_import")

package(default_visibility = ["//visibility:public"])

java_import(
    name = "dbusjava",
    jars = ["dbusjava.jar"],
)

java_import(
    name = "ev3classes",
    jars = ["ev3classes.jar"],
)

java_import(
    name = "websocket",
    jars = ["Java-WebSocket-1.5.3.jar"],
)

java_import(
    name = "slf4j-api",
    jars = ["slf4j-api-1.7.25.jar"],
)

java_import(
    name = "slf4j-simple",
    jars = ["slf4j-simple-1.7.25.jar"],
)